spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/interview_demo
    hikari:
      username: root
      password: mima4Mysql.123
      jdbc-url: jdbc:mysql://127.0.0.1:3306/interview_demo
  mvc:
    servlet:
      path: /interview-demo

